spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/developers
    password: EwersonPutkin82!
    username: root
